import type { Metadata } from "next";
import { Sono, JetBrains_Mono } from "next/font/google";
import NextTopLoader from "nextjs-toploader";
import "./globals.css";

import Header from "../components/header";
import Footer from "../components/footer";

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
});

const sono = Sono({
  variable: "--font-sono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark apply-transition">
      <body
        className={`${sono.variable} ${jetbrainsMono.variable} antialiased apply-transition`}
      >
        <NextTopLoader color="currentColor" />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
