import {
  PaletteIcon,
  CursorClickIcon,
  CardsIcon,
  FlagIcon,
  TerminalIcon,
  ListBulletsIcon,
  ClockUserIcon,
  HourglassMediumIcon,
  SpinnerIcon,
  ClockIcon,
  PaintRollerIcon,
  PaintBrushIcon,
} from "@phosphor-icons/react/dist/ssr";
import { SidebarLink } from ".";

export const types_links: SidebarLink[] = [
  {
    href: "/docs/types/any-color",
    title: "AnyColor",
    icon: PaletteIcon,
    type: "types",
    tag: "new",
  },
  {
    href: "/docs/types/extended-color",
    title: "ExtendedColor",
    icon: PaletteIcon,
    type: "types",
    tag: "new",
  },
  {
    href: "/docs/types/eight-bit-color-value",
    title: "EightBitColorValue",
    icon: PaletteIcon,
    type: "types",
    tag: "new",
  },
  {
    href: "/docs/types/rgb-color-value",
    title: "RGBColorValue",
    icon: PaletteIcon,
    type: "types",
    tag: "new",
  },
  {
    href: "/docs/types/button-group-events",
    title: "ButtonGroupEvents",
    icon: CursorClickIcon,
    type: "types",
  },
  {
    href: "/docs/types/button-group-options",
    title: "ButtonGroupOptions",
    icon: CursorClickIcon,
    type: "types",
  },
  {
    href: "/docs/types/button-options",
    title: "ButtonOptions",
    icon: CursorClickIcon,
    type: "types",
  },
  {
    href: "/docs/types/card-options",
    title: "CardOptions",
    icon: CardsIcon,
    type: "types",
  },
  {
    href: "/docs/types/card-width",
    title: "CardWidth",
    icon: CardsIcon,
    type: "types",
  },
  {
    href: "/docs/types/debug-level",
    title: "DebugLevel",
    icon: FlagIcon,
    type: "types",
  },
  {
    href: "/docs/types/input-events",
    title: "InputEvents",
    icon: TerminalIcon,
    type: "types",
  },
  {
    href: "/docs/types/input-options",
    title: "InputOptions",
    icon: TerminalIcon,
    type: "types",
  },
  {
    href: "/docs/types/input-style-options",
    title: "InputStyleOptions",
    icon: TerminalIcon,
    type: "types",
  },
  {
    href: "/docs/types/input-type",
    title: "InputType",
    icon: TerminalIcon,
    type: "types",
  },
  {
    href: "/docs/types/menu-events",
    title: "MenuEvents",
    icon: ListBulletsIcon,
    type: "types",
  },
  {
    href: "/docs/types/menu-item-options",
    title: "MenuItemOptions",
    icon: ListBulletsIcon,
    type: "types",
  },
  {
    href: "/docs/types/menu-options",
    title: "MenuOptions",
    icon: ListBulletsIcon,
    type: "types",
  },
  {
    href: "/docs/types/progress-events",
    title: "ProgressEvents",
    icon: ClockUserIcon,
    type: "types",
  },
  {
    href: "/docs/types/progress-label-pair",
    title: "ProgressLabelPair",
    icon: CardsIcon,
    type: "types",
  },
  {
    href: "/docs/types/progress-options",
    title: "ProgressOptions",
    icon: HourglassMediumIcon,
    type: "types",
  },
  {
    href: "/docs/types/progress-bar-options",
    title: "ProgressBarOptions",
    icon: HourglassMediumIcon,
    type: "types",
    tag: "updated",
  },
  {
    href: "/docs/types/progress-bar-state-color",
    title: "ProgressBarStateColor",
    icon: PaletteIcon,
    type: "types",
  },
  {
    href: "/docs/types/progress-status",
    title: "ProgressStatus",
    icon: ClockIcon,
    type: "types",
  },
  {
    href: "/docs/types/section-options",
    title: "SectionOptions",
    icon: PaintRollerIcon,
    type: "types",
  },
  {
    href: "/docs/types/spinner-options",
    title: "SpinnerOptions",
    icon: SpinnerIcon,
    type: "types",
  },
  {
    href: "/docs/types/spinner-style-options",
    title: "SpinnerStyleOptions",
    icon: SpinnerIcon,
    type: "types",
  },
  {
    href: "/docs/types/style-options",
    title: "StyleOptions",
    icon: PaintBrushIcon,
    type: "types",
    tag: "updated",
  },
  {
    href: "/docs/types/unspecified-color",
    title: "UnSpecifiedColor",
    icon: PaletteIcon,
    type: "types",
    tag: "updated",
  },
  {
    href: "/docs/types/alignment",
    title: "Alignment",
    icon: TerminalIcon,
    type: "types",
  },
  {
    href: "/docs/types/body-options",
    title: "BodyOptions",
    icon: CardsIcon,
    type: "types",
  },
  {
    href: "/docs/types/border-options",
    title: "BorderOptions",
    icon: CardsIcon,
    type: "types",
  },
  {
    href: "/docs/types/border-style",
    title: "BorderStyle",
    icon: CardsIcon,
    type: "types",
  },
  {
    href: "/docs/types/border-symbol-style",
    title: "BorderSymbolStyle",
    icon: CardsIcon,
    type: "types",
  },
  {
    href: "/docs/types/card-border-symbols",
    title: "CardBorderSymbols",
    icon: CardsIcon,
    type: "types",
  },
  {
    href: "/docs/types/fixed-position",
    title: "FixedPosition",
    icon: TerminalIcon,
    type: "types",
  },
  {
    href: "/docs/types/progress-update-options",
    title: "ProgressUpdateOptions",
    icon: HourglassMediumIcon,
    type: "types",
  },
  {
    href: "/docs/types/ratio",
    title: "Ratio",
    icon: TerminalIcon,
    type: "types",
  },
  {
    href: "/docs/types/terminal-dimensions",
    title: "TerminalDimensions",
    icon: TerminalIcon,
    type: "types",
  },
];
